---
abstract: 'Provide plain ASCII transliterations of Unicode text'
author:
  - 'Sean Burke <sburke@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Unidecode
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.008
version: 1.22
